//
//  GameModelController.swift
//  Relentless
//
//  Created by Yi Wai Chow on 14/3/20.
//  Copyright © 2020 OurNameIs. All rights reserved.
//

import Foundation

/// To handle `Model` related game actions
protocol GameModelController {

    func addItem(item: Item)

    func removeItem(item: Item)

    /// To be used by `Network` to receive orders generated by host
    func addOrder(order: Order)

    func addPackage(package: Package)

    func removePackage(package: Package)

    func deliverPackage(package: Package, to house: House)

    //func retrieveOrders(for house: House) -> [Order]

    func openPackage(package: Package)

}
